### PR TITLE
#9 - app name icon

### LINKED ISSUE #9: App name icon
Change app name to E-motion and add icon.

### PR DESCRIPTION
**Pull request by Lee0z**
It should close #9.
- Changed app name from template to "E-motion".
- Changed app icon from default flutter to:
image

### CODE REVIEW

**Review by EwelinaSkrzypacz — COMMENTED** [review]
1. For me (on emulator phone Pixel 3a, after reinstalling the app, the icon is the same as it was - I mean it's just default Flutter icon.

image

2. When I run command `flutter pub get` I see

image

Can me make something with it?

3. I noticed that branch with project-skeleton wasn't deleted after merging pr - it should be like that?

**Comment by Lee0z** [comment]
@EwelinaSkrzypacz 

1. It's now fixed
2. As I can see, it is normal behaviour even on freshly started project, here's flutter developer answer:
image
source:https://github.com/flutter/flutter/issues/109977
Also upgraded one dependency, same on #3.

3. Thank You for noticing the problem, setting has to be changed in repo by code owner. https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

**Review by EwelinaSkrzypacz — COMMENTED** [review]
For me it looks like that - it's okay, so approve. Maybe icon should be on transparent background? I won't nitpick about that, if design is like this.

image

**Comment by Lee0z** [comment]
Transparent design wasn't eye pleasing on iOS, so I left it like this.

**Review by EwelinaSkrzypacz — APPROVED** [review]

**Review by AleksandraKozubal — APPROVED** [review]

**Pull request merged**
