### PR TITLE
#11 - add main page

### LINKED ISSUE #11: Add main page
Add main page with functionalities as in previous web app, but

-  add sorting
-  add share button (connected to preset links, copies link to clipboard)
-  map should present cities/countries' names in language choosen on website (if possible)

### PR DESCRIPTION
**Pull request by Lee0z**
It should close #11.

### CODE REVIEW

**Comment by Lee0z** [comment]
Add at frontend:

- main page

image

- hambuger navbar

image

- login modal

image

- register modal

image

**Comment by Lee0z** [comment]
- updated view - now it shows data from api
image

**Review by JakubKermes — DISMISSED** [review]

**Comment by Lee0z** [comment]
- update cosmetics
image

**Review by JakubKermes — DISMISSED** [review]

**Comment by Lee0z** [comment]
- updated cosmetics, moved logo to left.
image

**Review by JakubKermes — APPROVED** [review]

**Review by AleksandraKozubal — APPROVED** [review]

**Pull request merged**
